#!/usr/bin/env python3
# Copyright (c) 2026 Advanced Micro Devices, Inc.
# Author: Jeff Daily <jeff.daily@amd.com>
#
# Generate override stubs for the TensorRT apiv V-classes. Each public nvinfer1
# interface (IBuilder, ICudaEngine, ...) forwards to a protected apiv::VXxx
# pure-virtual class declared in NvInferImpl.h. The shim implements the few
# methods on the critical path by hand and needs trivial stubs for the rest.
# This script reads NvInferImpl.h and emits, per V-class, a .stubs.inc of
# override definitions for every pure virtual NOT in that class's hand-written
# exclude set. The .inc is #included inside the shim class body.
#
# Stub bodies: reference returns abort via trtshim_die (never reached on the
# supported path); everything else logs once and returns a default. getPImpl
# returns `this`.

import re
import sys
from pathlib import Path

# Methods implemented by hand in shim.cpp, excluded from generation.
EXCLUDE = {
    "VBuilder": {"createBuilderConfig", "createNetworkV2", "buildSerializedNetwork",
                 "getLogger", "getPImpl"},
    "VNetworkDefinition": {"getInput", "getOutput", "getNbInputs", "getNbOutputs",
                           "getPImpl", "getName"},
    "VBuilderConfig": {"setFlag", "getFlag", "clearFlag", "getPImpl",
                       "setInt8Calibrator", "getInt8Calibrator",
                       "addOptimizationProfile", "getNbOptimizationProfiles"},
    "VRuntime": {"deserializeCudaEngine", "getLogger", "getPImpl"},
    "VCudaEngine": {"getNbIOTensors", "getIOTensorName", "getTensorShape",
                    "getTensorDataType", "getTensorIOMode",
                    "getTensorComponentsPerElement", "getTensorVectorizedDim",
                    "getTensorBytesPerComponent", "createExecutionContext",
                    "createExecutionContextWithoutDeviceMemory", "serialize",
                    "getName", "getNbLayers", "getPImpl"},
    "VExecutionContext": {"setTensorAddress", "executeV2", "enqueueV3",
                          "setInputShape", "getPImpl"},
    "VHostMemory": {"data", "size", "type"},
    "VTensor": {"getDimensions", "getName", "setName", "getType", "getPImpl"},
}

CLASSES = list(EXCLUDE.keys())


def class_body(text, cls):
    m = re.search(r"\bclass %s\b[^{]*\{(.*?)\n\};" % re.escape(cls), text, re.S)
    if not m:
        raise SystemExit("class %s not found" % cls)
    return m.group(1)


def split_decls(body):
    # Drop comments, collapse whitespace, split on ';'.
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    for chunk in body.split(";"):
        chunk = " ".join(chunk.split())
        if "= 0" not in chunk:
            continue
        # A chunk may carry a leading access-specifier (e.g. "public: virtual
        # ...") on the first method; start at the "virtual" keyword.
        idx = chunk.find("virtual")
        if idx >= 0:
            yield chunk[idx:]


DECL_RE = re.compile(
    r"^virtual\s+(?P<ret>.+?)\s+(?P<name>~?\w+)\s*\((?P<args>.*)\)\s*"
    r"(?P<quals>(?:const\s*)?(?:noexcept\s*)?)\s*=\s*0$"
)


def strip_defaults(args):
    # Remove default argument initializers; they may not be repeated on an
    # override definition.
    out, depth, i, n = [], 0, 0, len(args)
    while i < n:
        c = args[i]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        if c == "=" and depth == 0:
            # skip until top-level comma
            i += 1
            while i < n and not (args[i] == "," and depth == 0):
                if args[i] in "([{":
                    depth += 1
                elif args[i] in ")]}":
                    depth -= 1
                i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def default_body(ret, qname):
    ret = ret.strip()
    if "&" in ret:  # reference return: cannot synthesize; abort if reached
        return '{ ::trtshim::trtshim_die("%s"); }' % qname
    log = '::trtshim::trtshim_unimpl("%s"); ' % qname
    if ret == "void":
        return "{ %s}" % log
    if ret == "bool":
        return "{ %sreturn false; }" % log
    if ret.endswith("*"):
        return "{ %sreturn nullptr; }" % log
    if re.fullmatch(r"(unsigned\s+)?(int|short|long|char)|"
                    r"(u?int(8|16|32|64)_t)|size_t|float|double", ret):
        return "{ %sreturn 0; }" % log
    return "{ %sreturn {}; }" % log  # enums, Dims, by-value structs


def gen_class(text, cls):
    excl = EXCLUDE[cls]
    lines = ["// Generated by tools/gen_stubs.py from NvInferImpl.h -- do not edit.",
             "// Stub overrides for %s methods implemented by hand elsewhere." % cls]
    for decl in split_decls(class_body(text, cls)):
        m = DECL_RE.match(decl)
        if not m:
            raise SystemExit("could not parse in %s: %r" % (cls, decl))
        name = m.group("name")
        if name in excl or name.startswith("~"):
            continue
        ret, args, quals = m.group("ret"), m.group("args"), m.group("quals").strip()
        args = strip_defaults(args)
        qname = "%s::%s" % (cls, name)
        if name == "getPImpl":
            body = "{ return this; }"
        else:
            body = default_body(ret, qname)
        sig = "%s %s(%s)%s%s override %s" % (
            ret, name, args, " " if quals else "", quals, body)
        lines.append(sig)
    return "\n".join(lines) + "\n"


def main():
    impl = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    text = impl.read_text()
    for cls in CLASSES:
        (outdir / (cls + ".stubs.inc")).write_text(gen_class(text, cls))
        print("wrote", outdir / (cls + ".stubs.inc"))


if __name__ == "__main__":
    main()
